### ISSUE TITLE
Access denied, LOAD DATA INFILE  

### ISSUE THREAD

**Issue by jo91** [andreask7/lwt#17] opened 2016-03-07 23:37 UTC
It seems LOAD DATA INFILE isn't available on some shared hosting services. At least it is blocked at hostgator. Any workaround?

Fatal Error in SQL Query: LOAD DATA INFILE '/tmp/lwt/tmpti.txt' INTO TABLE temptextitems FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n' (@c) set TiOrder = if(@c="\r",@a,@a:=@a+1), TiText = @c, TiSeID = if(@c="\r",@b:=@b+1,@b),TiWordCount=('¶.!?:;。！？：；' not like concat("%",@c,"%")) and (!(@c rlike '[^一-龥]+')), TiCount = IF(@c="\r",(@d:= 0), (@d:=@d+CHAR_LENGTH(@c))+1-CHAR_LENGTH(@c))

Error Code & Message: [1045] Access denied for user '************'@'localhost' (using password: YES)

**Comment by andreask7** [comment] 2016-03-08 18:04
Hello jo91,

can you change `LOAD DATA INFILE` into `LOAD DATA LOCAL INFILE` in utilities.inc.php (line:3237) and check if it works

**Comment by jo91** [comment] 2016-03-08 19:45
Thanks for the quick answer. I will try it later. I moved now to Linode, so it isn't an issue for me anymore.
By the way, in your version 1.6.27, when setting "Make each charachter a word" , an empty space is inserted between each word. (see demo-database chinese ) . Is this a feature or a bug?

**Comment by feanarosurion** [comment] 2016-03-09 17:54
I can confirm this issue. It only started since updated to 1.6.27. Just a report, I haven't done any further digging at this time.

**Comment by feanarosurion** [comment] 2016-03-10 00:12
Tried the suggested fix. Below is my error:

Fatal Error in SQL Query: LOAD DATA LOCAL INFILE '/tmp/lwt/tmpti.txt' INTO TABLE temptextitems FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n' (@c) set TiOrder = if(@c="\r",@a,@a:=@a+1), TiText = @c, TiSeID = if(@c="\r",@b:=@b+1,@b),TiWordCount=('¶.!?:;' not like concat("%",@c,"%")) and (!(@c rlike '[^\\-\\\'a-zA-ZÀ-ÖØ-öø-ȳЀ-ӹ]+')), TiCount = IF(@c="\r",(@d:= 0), (@d:=@d+CHAR_LENGTH(@c))+1-CHAR_LENGTH(@c))
Error Code & Message: [1267] Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation 'regexp'

**Comment by feanarosurion** [comment] 2016-03-10 00:47
So I guess by clarification, the suggested fix worked as far as permissions go but it looks like the database has a collations issue. Tried reverting back to version 1.6.24 and now there's a column error problem.

**Comment by jo91** [comment] 2016-03-10 10:03
I got the same error. There is an easy fix.
Go to phpmyadmin. In operation tab change the collation of your database from latin1_swedish_ci to utf8_general_ci. Now it should work

**Comment by feanarosurion** [comment] 2016-03-11 00:35
Thanks for the tip jo91! That worked. Issue is fixed with the combination of collation and the LOCAL permission in the SQL as suggested.

**Closed** 2016-04-21 19:04 UTC
